spring:
  profiles:
    active: dev # 默认激活 dev 配置文件 (application-dev.yml)
    
  sql:
    init:
      mode: always # 强制初始化
      schema-locations: classpath:schema.sql # 显式引导点火路径
      
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名自动映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 在控制台打印被生成的 SQL 语句，方便纠错
